# Xóa dòng version: '3.8' để tránh cảnh báo "obsolete"
x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__LOGGING_LEVEL: INFO
    PYTHONPATH: /opt/airflow/scripts
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/scripts:/opt/airflow/scripts
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/data:/opt/airflow/data
    - ./airflow/requirements.txt:/requirements.txt
  user: "${AIRFLOW_UID:-1000}:0"
  networks: # Gán mạng chung vào common để các service Airflow đều thấy nhau
    - shared-network
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: bash -c "airflow db init && airflow users create --username airflow --password airflow --firstname Admin --lastname Admin --role Admin --email admin@example.com"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_PASSWORD: 'airflow'
  minio:
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/minio_storage:/data
    env_file:
      - ./minio/.env
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - shared-network

# ĐÂY LÀ PHẦN QUAN TRỌNG: Tự động tạo mạng
networks:
  shared-network:
    driver: bridge